name: Update Movies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download JSON file
        run: |
          curl -L http://files.tmdb.org/p/exports/movie_ids_05_15_2024.json.gz -o movies.json.gz
          gunzip movies.json.gz

      - name: Install dependencies
        run: |
          sudo apt-get install -y jq

      - name: Process JSON and Sync with Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          # Extract a random movie ID from JSON
          MOVIE_ID=$(jq -r '.[] | select(.id != null) | .id' movies.json | shuf -n 1)

          # Check if movie ID exists in Supabase
          MOVIE_EXISTS=$(curl -s -X GET "$SUPABASE_URL/rest/v1/keyword_movie_of_the_day?select=id&movie_id=eq.$MOVIE_ID" \
            -H "apikey:$SUPABASE_KEY" -H "Authorization: Bearer $SUPABASE_KEY" | jq '. | length')

          if [ "$MOVIE_EXISTS" -eq 0 ]; then
            # Insert movie ID into Supabase
            curl -s -X POST "$SUPABASE_URL/rest/v1/keyword_movie_of_the_day" \
              -H "Content-Type: application/json" \
              -H "apikey:$SUPABASE_KEY" \
              -H "Authorization: Bearer $SUPABASE_KEY" \
              -d '{"movie_id": '$MOVIE_ID'}'
          else
            echo "Movie ID $MOVIE_ID already exists in Supabase"
          fi
