name: Update Movies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download JSON file
        run: |
          curl -L http://files.tmdb.org/p/exports/movie_ids_05_15_2024.json.gz -o movies.json.gz
          gunzip movies.json.gz

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Process JSON and Sync with Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          # Check the JSON structure
          echo "Checking JSON structure..."
          head -n 10 movies.json

          # Extract a random movie ID from JSON
          MOVIE_ID=$(jq -r '.id' movies.json | shuf -n 1)
          if [ -z "$MOVIE_ID" ]; then
            echo "No movie ID found."
            exit 1
          fi

          echo "Selected Movie ID: $MOVIE_ID"

          # Call Supabase function to insert movie ID if not exists
          RESPONSE=$(curl -s -w "%{http_code}" -o response.json -X POST "$SUPABASE_URL/rest/v1/rpc/insert_movie_if_not_exists" \
            -H "Content-Type: application/json" \
            -H "apikey:$SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY" \
            -d '{"p_movie_id": '"$MOVIE_ID"'}')

          HTTP_CODE=$(echo $RESPONSE | tail -n1)
          BODY=$(cat response.json)

          if [ "$HTTP_CODE" -ne 200 ]; then
            echo "Error: HTTP $HTTP_CODE"
            echo "Response Body: $BODY"
            exit 1
          fi

          echo "Processed Movie ID $MOVIE_ID"
